default_stages: [pre-commit, pre-push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-json
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-xml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: requirements-txt-fixer
  - repo: https://github.com/crate-ci/typos
    rev: v1.22.9
    hooks:
      - id: typos
  - repo: https://github.com/commitizen-tools/commitizen # better commit messages
    rev: v1.17.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/astral-sh/ruff-pre-commit # python lint + format
    rev: v0.5.0
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]
        stages: [pre-commit, pre-push]
      - id: ruff-format
        types_or: [python, pyi, jupyter]
    # all the stuff after this comment is slow, so it is ran only on pushes
  - repo: local
    hooks:
        # it is important to run this hook before pyright, to sync the venv
      - id: python-deps
        name: Install python deps
        stages: [pre-push]
        types: [python, pyi, jupyter]
        entry: poetry install
        language: system
        pass_filenames: false
        always_run: true
  - repo: https://github.com/RobertCraigie/pyright-python # python typecheck
    rev: v1.1.370
    hooks:
    - id: pyright
      stages: [pre-push]
      types_or: [python, pyi, jupyter]
  - repo: local
    hooks:
      - id: pytest # testing: but only on push (nice)
        name: Testing with pytest
        stages: [pre-push]
        types: [python, pyi, jupyter]
        entry: poetry run pytest -v .
        language: system
        pass_filenames: false
        always_run: true
